[package]
name = "go-duration"
version = "0.1.0"
edition = "2021"

[features]
default = ["serde"]
serde = ["dep:serde"]

[dependencies]
nom = { version = "7", default-features = false }
serde = { version = "1", optional = true, features = ["derive"] }
thiserror = "1"

[dev-dependencies]
serde_test = "1"
serde_json = "1"
