[package]
name = "go-duration"
version = "0.1.0"
edition = "2021"

# [features]
# serde = ["dep:serde"]

[dependencies]
nom = { version = "7.1.3", default-features = false }
serde = { version = "1.0.171", optional = false }
